### ISSUE TITLE
unrecognized subsystem: 'excelrequirements'

### ISSUE THREAD

**Issue by LorneCash** [snuziale/vsts-open-in-excel#2]
I installed the 2015 Office Integration 3.1 and that works great I can pull a query from there no problems. However, when on the VSTS web page and I click the Open in Excel button I get this error:
---------------------------
Error
---------------------------
TF400051: Cannot process URL tfs://ExcelRequirements/OpenQuery?cn=https://xxxxxxxxxx.visualstudio.com/DefaultCollection/&proj=xxxxxxxxxxxxxx&qid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx because it contains an unrecognized subsystem: 'excelrequirements'.
---------------------------
OK 
---------------------------

I've tried Chrome and IE and both give the same error.

My Excel is part of Office 2016 Professional Plus (x64).

Any help would be greatly appreciated.

**Comment by snuziale** [comment]
Hi LorneCash,

This error is a result of not having the most recent visual studio "15" client installed.
You can download the prerelease version here:
https://www.visualstudio.com/visual-studio-pre-release-downloads/

_Details: The tfs protocol handler needs to be updated to know how to support the newly added url format (shown in your comment above)._ 

Thanks,
-Sam

**Comment by nschonni** [comment]
Just cross linking this since this is another reason you might see it if you have multiple Visual Studio versions installed https://developercommunity.visualstudio.com/content/problem/87832/open-in-excel-extension-getting-tf400051-cannot-pr.html
